spring:
  application:
    name: applicants-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:file:./.env

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000

refresh-token:
  duration: 10080m