spring:
  application:
    name: applicants-service
  datasource:
    url: jdbc:postgresql://localhost:5432/interactive-map-db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none